### ISSUE TITLE
请问您做的工作是否是基于超表面的快照成像呢？

### ISSUE THREAD

**Issue by zhanglei-1997** [ZhangJC-2k/SSR#1]

**Comment by ZhangJC-2k** [comment]
您好，不是的，这个工作做的是传统的光谱快照压缩成像，像MST，DAUHST等工作一样。

**Comment by zhanglei-1997** [comment]
好的，感谢您的回复

---- 回复的原邮件 ----
| 发件人 | Zhang ***@***.***> |
| 发送日期 | 2024年05月16日 13:19 |
| 收件人 | ZhangJC-2k/SSR ***@***.***> |
| 抄送人 | zhanglei-1997 ***@***.***>,
Author ***@***.***> |
| 主题 | Re: [ZhangJC-2k/SSR] 请问您做的工作是否是基于超表面的快照成像呢？ (Issue #1) |

您好，不是的，这个工作做的是传统的光谱快照压缩成像，像MST，DAUHST等工作一样。
