### ISSUE TITLE
您好，下载训练数据集的时候显示提取码错误，可以麻烦您更新一下吗？

### ISSUE THREAD

**Issue by tt-798** [ZhangJC-2k/SSR#2]

**Comment by ZhangJC-2k** [comment]
感谢提醒，我加了一个新的[下载链接](https://pan.baidu.com/s/1gyIOfmUWKrjntKobUjwTjw?pwd=lup6)，你看一下能否下载。提取码错误这个我给他们说一下，再次感谢。

**Comment by tt-798** [comment]
可以下载的，十分感谢~~
