### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by wrtg666** [ZhangJC-2k/SSR#3]
您好我想问下这里的mask值形如这样
![image](https://github.com/user-attachments/assets/0a9b6613-a5d0-403b-b48d-c8db6430c4ed)
有1，还有(0-1)之间的数，为什么不是用只有0和1的矩阵来代表掩膜呢？

**Comment by ZhangJC-2k** [comment]
在理想中这个掩膜是由01组成的，但因为实际制作的掩膜会有一些误差，会使得掩膜的值在01之间有所偏移，所以就出现了这种情况。（当前的方法也普遍采用真实的掩膜用于实验）

**Comment by wrtg666** [comment]
谢谢解答！
![image](https://github.com/user-attachments/assets/a38a1fe3-6196-41b6-8895-6cec3cee26ee)
h
还有就是这里针对Phi_s_batch的一系列操作是为什么呀

**Comment by wrtg666** [comment]
HSI[HSI < 0.] = 0.
    HSI[HSI > 1.] = 1.
    直接这么处理HSI数据会不会有损失吗

**Comment by ZhangJC-2k** [comment]
感谢提问，Phi_s_batch的一系列操作是为了预计算公式中Phi乘Phi^T。然后因为Phi乘Phi^T在分母上，还要避免除0。

HSI[HSI < 0.] = 0.
HSI[HSI > 1.] = 1.
这个是规范化数据，避免一些异常值。可能在实际应用中会有一点点损失，但对我们训练测试来说影响不大。

**Comment by wrtg666** [comment]
十分感谢答疑解惑！

**Comment by wrtg666** [comment]
您好，我想问下为什么用.pkl保存模型参数而不是.pth吖？还有就是不能接着上一次训练得到的模型参数继续训练，得清空删掉Checkpoint里面的文件才能正常训练（从头来）

**Comment by ZhangJC-2k** [comment]
.pkl和.pth都可以的，只要代码整体风格保持一致就行。我们的代码是可以继续训练的，你在这个过程中遇到了什么问题吗？比如你在第9轮训练断掉，这个时候再运行python Train.py会使用缓存的第8轮的权重继续开始第9轮的训练。不过要注意断掉后再继续训练会造成最终性能下降。

**Comment by wrtg666** [comment]
我把第9轮的权重文件删掉后可以继续训练了，谢谢！
我看好像类似工作论文所使用的数据集都是CAVE或者KAIST居多，都是先模拟CASSI的过程，得到simulated data再进行重建工作，似乎实际用CASSI设备得到实测数据只有20年的这篇End-to-End Low Cost Compressive (TSA-Net) ？

**Comment by ZhangJC-2k** [comment]
是的，当前的实测数据主要还是TSA-Net那个数据集。袁老师那边之后可能会放出更多数据集，可以关注一下他们的工作。

**Comment by wrtg666** [comment]
好的好的，谢谢！

**Comment by wrtg666** [comment]
您好，我想问下在train文件中参数设置为parser.add_argument("--trainset_num", default=5000, type=int, help='The number of training samples of each epoch')
而在Test文件中参数设置为parser.add_argument("--trainset_num", default=20000, type=int, help='The number of training samples of each epoch')这是为什么啊？

**Comment by ZhangJC-2k** [comment]
这个是不相关的参数，很久之前写的，不用在意，Train里的testset_num参数和Test里的trainset_num参数在运行过程中都不会被用到。

**Comment by wrtg666** [comment]
收到，谢谢！
