### ISSUE TITLE
LN 和 GN

### ISSUE THREAD

**Issue by chenjiachengzzz** [ZhangJC-2k/SSR#5]
作者您好，我想咨询您一下，为啥有的地方使用 LN，有的地方使用 GN，是因为使用 GN 效果会更好吗？

**Comment by ZhangJC-2k** [comment]
感谢提问，这是一个很好的问题。这个设计主要是为了让训练过程更加稳定，如果只使用LN训练会出现跑飞的情况。我们考虑这可能和网络里一些独特的设计（如通道压缩）有关系，而LN主要是通道维度的归一化，可能不会很好发挥作用。然后我们尝试采用不同方向的归一化也就是GN去尝试，并且最后实现了稳定的训练。

**Comment by chenjiachengzzz** [comment]
> 感谢提问，这是一个很好的问题。这个设计主要是为了让训练过程更加稳定，如果只使用LN训练会出现跑飞的情况。我们考虑这可能和网络里一些独特的设计（如通道压缩）有关系，而LN主要是通道维度的归一化，可能不会很好发挥作用。然后我们尝试采用不同方向的归一化也就是GN去尝试，并且最后实现了稳定的训练。

好的，明白了，感谢作者的解惑！
